include: package:flutter_lints/flutter.yaml

formatter:
  trailing_commas: preserve

analyzer:
  errors:
    prefer_initializing_formals: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mapper.dart"
    - lib/generated_plugin_registrant.dart

linter:
  rules:
    prefer_const_constructors: true
