name: jpnese2u
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_mlkit_text_recognition: ^0.15.1
  platform_ocr:
    git:
      url: https://github.com/chuongch-pivot/platform_ocr.git
      ref: main
  window_manager: ^0.5.2
  tray_manager: ^0.5.3
  flutter_macos_permissions: ^2.0.8
  permission_handler: ^12.0.3
  screen_capturer: ^0.2.3
  dio: ^5.10.0
  retrofit: ^4.9.2
  logger: ^2.7.0
  json_annotation: ^4.12.0
  kuromoji:
    git:
      url: https://github.com/chuongch-pivot/kuromoji.git
      ref: mistress
  envied: ^1.3.8
  dart_mappable: ^4.8.0
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^10.3.1
  shared_preferences: ^2.5.5
  desktop_multi_window: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  flutter_gen_runner: ^5.14.1
  retrofit_generator: ^10.2.7
  json_serializable: ^6.14.0
  envied_generator: ^1.3.8
  dart_mappable_builder: ^4.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/tray_icon.png
